  <%//@ page language="java" contentType="text/html;charset=euc-kr"%>
  <input type='hidden' name="s_width" value="<%=s_width%>">   
  <input type='hidden' name="s_height" value="<%=s_height%>">     
  <input type='hidden' name="sh_height" value="<%=sh_height%>">   
  <input type='hidden' name='auth_rw' value='<%=auth_rw%>'>
  <input type='hidden' name='br_id' value='<%=br_id%>'>
  <input type='hidden' name='user_id' value='<%=user_id%>'>    
  <input type='hidden' name='s_kd'  value='<%=s_kd%>'>
  <input type='hidden' name='t_wd' value='<%=t_wd%>'>
  <input type='hidden' name='t_wd1' value='<%=t_wd1%>'>
  <input type='hidden' name='t_wd2' value='<%=t_wd2%>'>
  <input type='hidden' name='s_br' value='<%=s_br%>'>
  <input type='hidden' name='gubun1' value='<%=gubun1%>'>
  <input type='hidden' name='gubun2' value='<%=gubun2%>'>
  <input type='hidden' name='gubun3' value='<%=gubun3%>'>
  <input type='hidden' name='gubun4' value='<%=gubun4%>'>
  <input type='hidden' name='gubun5' value='<%=gubun5%>'>
  <input type='hidden' name='gubun6' value='<%=gubun6%>'>  
  <input type='hidden' name='chk1' value='<%=chk1%>'>
  <input type='hidden' name='chk2' value='<%=chk2%>'>
  <input type='hidden' name='chk3' value='<%=chk3%>'>
  <input type='hidden' name='chk4' value='<%=chk4%>'>
  <input type='hidden' name='chk5' value='<%=chk5%>'>  
  <input type='hidden' name='chk6' value='<%=chk6%>'>  
  <input type='hidden' name='chk7' value='<%=chk7%>'>      
  <input type='hidden' name='st_dt' value='<%=st_dt%>'>
  <input type='hidden' name='end_dt' value='<%=end_dt%>'>
  <input type='hidden' name='sort' value='<%=sort%>'>
  <input type='hidden' name='asc' value='<%=asc%>'>